name = "shakthisangitasabha"
compatibility_date = "2026-02-08"

[build]
command = "curl -L https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_linux-amd64.tar.gz | tar xz && npm install && ./hugo --minify"

[assets]
directory = "./public"
