name = "shakthisangitasabha"
pages_build_output_dir = "public"
compatibility_date = "2023-11-04"

[env.production.vars]
ARGS = "--minify --baseURL https://shakthisangitasabha.com"
HUGO_VERSION = "0.145.0"
